version: "3.9"
services:
  web:
    build: .
    container_name: ticket-system-web
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
    # Uncomment to use a .env file
    # env_file:
    #   - ./.env
    restart: unless-stopped
